version: '3'
services:
    employees-mongodb:
        image: mongo
        ports:
            - 27017:27017
    consul:
        image: consul
        ports:
            - 8500:8500
    employees:
        image: employees:0.1
        environment:
            MICRONAUT_SERVER_HOST: employees
            MICRONAUT_SERVER_PORT: 8080
            MONGO_HOST: employees-mongodb
            MONGO_PORT: 27017
            CONSUL_HOST: consul
            CONSUL_PORT: 8500
        links:
            - employees-mongodb
            - consul
        ports:
            - 8080:8080
        depends_on:
            - employees-mongodb
