---
micronaut:
  application:
    name: employees

---
hystrix:
  stream:
    enabled: false
---
postgres:
  reactive:
    client:
      port: 5432
      host: localhost
      database: employees
#      user: user
#      password: password
#      maxSize: 5
