---
micronaut:
  application:
    name: employees
---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
---
consul:
  client:
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
---
employees:
  database:
    name: employees
  api:
    version: v1
